#!/bin/bash

# Specs:
# ./magic
#     - puts all the files in place

# Helper to make things pretty

function log_msg() {
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    NORMAL=$(tput sgr0)
    MSG="$1"
    let COL=$(tput cols)-${#MSG}+${#GREEN}+${#NORMAL}

    printf "%s%${COL}s" "$MSG" "[$GREEN OK $NORMAL]"
}

# Main

log_msg "Starting up!"

# Vim
# Check if Vundle is downloaded; if not, clone it. Afterwards it updates itself
[ ! -d ~/.vim/bundle/Vundle.vim ] && git clone --quiet https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

mkdir -p ~/.vim/backup

mkdir -p ~/dotfiletemp/vim-molokai
git clone --quiet https://github.com/tomasr/molokai ~/dotfiletemp/vim-molokai
mkdir -p ~/.vim/colors/
cp ~/dotfiletemp/vim-molokai/colors/molokai.vim ~/.vim/colors/
cp vimrc ~/.vimrc
log_msg "Vim essentials in place"

# Neovim
mkdir -p ~/.config/
cp -r nvim ~/.config/
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
curl -fLo ~/.config/nvim/colors/monokai.vim --create-dirs \
    https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim
log_msg "Neovim initiated"


# i3 window manager
mkdir -p ~/.i3/
cp i3.conf ~/.i3/config
cp statusbar ~/.i3/statusbar
git clone --quiet https://github.com/olemartinorg/i3-alternating-layout ~/dotfiletemp/i3-alternating-layout
cp ~/dotfiletemp/i3-alternating-layout/alternating_layouts.py ~/.i3alternate.py
log_msg "Tossed around i3 window manager configurations"

# Fonts
log_msg "Starting a bigger task: fonts"
mkdir -p ~/.fonts/
mkdir -p ~/dotfiletemp/powerline-fonts
git clone --quiet https://github.com/powerline/fonts ~/dotfiletemp/powerline-fonts
rsync -a --exclude='.git' ~/dotfiletemp/powerline-fonts/ ~/.fonts/
fc-cache -f ~/.fonts/
log_msg "Re-cached font awesomeness"

# Terminal
mkdir -p ~/.config/alacritty/
cp alacritty.yml ~/.config/alacritty/
log_msg "Alacritty served, bon appetit"

# Shell
cp zshrc ~/.zshrc
cp promptline.sh ~/.promptline.sh
mkdir -p ~/.urxvt/ext/
git clone --quiet https://github.com/muennich/urxvt-perls ~/.urxvt/ext
log_msg "Boosted your shell efficiency"

# Git
cp gitconfig ~/.gitconfig
log_msg "Tweaked Git powers"

# Xresources
cp Xresources ~/.Xresources
log_msg "Extracted Xresources serum"

# Screenrc
cp screenrc ~/.screenrc
log_msg "Matching the screenrc"

# Tmux
cp tmux.conf ~/.tmux.conf
log_msg "Multiplexed multiplexers"

# npmrc
cp npmrc ~/.npmrc
log_msg "Put npmrc in place"

# muttrc
cp muttrc ~/.muttrc
log_msg "Put muttrc in place"

# scripts
mkdir -p ~/.bin/
cp upload ~/.bin/
log_msg "Copied some handy scripts"

# k9s
mkdir -p ~/.k9s/
cp k9s-skin.yml ~/.k9s/skin.yml
log_msg "Prettified k9s"

# topgrade
cp topgrade.toml ~/.config/topgrade.toml
log_msg "Put topgrade.toml in place"

# Cleanup
rm -rf ~/dotfiletemp
log_msg "Took out the trash"
