#!/bin/bash

# Specs:
# ./script install
#     - installs software described in requirements
# ./script update
#     - calls git pull in dotfiles repo
#     - puts all the files in place
# Main functions

function install {
    echo "Installing software:";
    echo $(parse_software);
    sudo apt-get install $(parse_software);
}

function update {
    log_msg "Starting up!"
    files;
}

# Helper functions

function parse_software {
    echo `sed -e 's/^#(.*)//g; s/\s*#.*$//g' requirements`;
}

function log_msg() {
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    NORMAL=$(tput sgr0)
    MSG="$1"
    let COL=$(tput cols)-${#MSG}+${#GREEN}+${#NORMAL}

    printf "%s%${COL}s" "$MSG" "[$GREEN OK $NORMAL]"
}

function files {
    # Vim
    # Check if Vundle is downloaded; if not, clone it. Afterwards it updates itself
    [ ! -d ~/.vim/bundle/Vundle.vim ] && git clone --quiet https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

    mkdir -p ~/.vim/backup

    mkdir -p ~/dotfiletemp/vim-molokai
    git clone --quiet https://github.com/tomasr/molokai ~/dotfiletemp/vim-molokai
    mkdir -p ~/.vim/colors/
    cp ~/dotfiletemp/vim-molokai/colors/molokai.vim ~/.vim/colors/
    cp vimrc ~/.vimrc
    log_msg "Vim essentials in place"

    # i3 window manager
    mkdir -p ~/.i3/
    cp i3.conf ~/.i3/config
    log_msg "Tossed around i3 window manager configurations"

    # Fonts
    log_msg "Starting a bigger task: fonts"
    mkdir -p ~/.fonts/
    mkdir -p ~/dotfiletemp/powerline-fonts
    git clone --quiet https://github.com/Lokaltog/powerline-fonts ~/dotfiletemp/powerline-fonts
    rsync -a --exclude='.git' ~/dotfiletemp/powerline-fonts/ ~/.fonts/
    fc-cache -f ~/.fonts/
    log_msg "Re-cached font awesomeness"

    # Shell
    cp zshrc ~/.zshrc
    cp promptline.sh ~/.promptline.sh
    log_msg "Boosted your shell efficiency"

    # Git
    cp gitconfig ~/.gitconfig
    log_msg "Tweaked Git powers"

    # Xresources
    cp Xresources ~/.Xresources
    log_msg "Extracted Xresources serum"

    # Screenrc
    cp screenrc ~/.screenrc
    log_msg "Matching the screenrc"

    # Tmux
    cp tmux.conf ~/.tmux.conf
    log_msg "Multiplexed multiplexers"

    # Cleanup
    rm -rf ~/dotfiletemp
    log_msg "Took out the trash"
}

case $1 in
"install")
    install
;;
"update")
    update
;;
*)
    echo "Usage: $0 update/install"
;;
esac
